const instrumentsArr = [
{    category : 'woodwinds',
    instreuments :"Flutes",
    price : 500},
    { category: "woodwinds",
    instrument : "Clarinet",
    price : 200},
    {
        category : "woodwinds",
        instrument : "Oboe",
        price 400},
{
    category: "brass",
    instrument :"Trumpet",
    price : 200
    },
    {
        category: "brass",
        instrument : "Trombone",
        price : 300
    },
    {
        category :"brass",
        instrument : "Fremch Horn",
        price : 4300
    },
    {
        category :"percussion",
        instrument: "Drum Set",
        price : 500
    },
    {
        category :"percussion",
        instrument :"Xylophone",
        price : 3000
    },
    {
        category :"percussion",
        instrument : "Cymbals",
        price: 200},
        {
            category: "percussion",
            instrument: "Marimba",
            price: 3000
        }
];

const selectContainer = document.querySelector{"select"}
const productContainer = document.querySelector{"products-container"};

selectContainer.addEventListener("change", ()=>
{console.log("this is a test")
}); 